"use client";

import { useState } from "react";
import { Sparkles, FileText, Copy, Check, Loader2 } from "lucide-react";

export default function Home() {
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    if (!topic.trim()) return;
    setLoading(true);
    setResult(null);

    // Demo mode - works without backend
    setTimeout(() => {
      const title = `The Complete Guide to ${topic.trim()}`;
      const content = `# ${title}

## Introduction

In today's fast-paced digital world, understanding **${topic}** has become more important than ever. Whether you are a beginner or looking to level up your skills, this comprehensive guide will walk you through everything you need to know.

## Why ${topic} Matters

${topic} plays a crucial role in modern business and personal growth. Companies that master it often see significant improvements in efficiency, engagement, and results.

Key benefits include:
- Improved productivity and focus
- Better decision making
- Competitive advantage in the market
- Long-term sustainable growth

## Getting Started

### Step 1: Understand the Fundamentals
Before diving deep, make sure you have a solid grasp of the core concepts.

### Step 2: Set Clear Goals
Define what success looks like for you. Having measurable goals will help you track progress.

### Step 3: Implement Best Practices
Consistency is key. Apply proven strategies and refine your approach based on results.

## Conclusion

Mastering ${topic} is a journey, not a destination. Stay curious, keep learning, and apply what you learn consistently.

---
*Generated by AI Content Generator • Portfolio Project by Rajiv Kapur*`;

      setResult({
        title,
        content,
        meta_description: `Discover everything about ${topic}. Expert tips and best practices for 2026.`,
        keywords: `${topic}, ${topic} guide, ${topic} tips`,
        seo_score: 82,
        word_count: content.split(" ").length,
      });
      setLoading(false);
    }, 1800);
  };

  const copyContent = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      {/* Navbar */}
      <nav className="bg-white/80 backdrop-blur border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-xl text-slate-800">AI Content Lab</span>
          </div>
          <span className="text-sm text-slate-500">by Rajiv Kapur</span>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-12">
        {/* Hero */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4">
            Generate SEO-Ready <span className="text-indigo-600">Blog Posts</span> with AI
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Enter a topic and get a complete, well-structured article with meta description and SEO score.
          </p>
        </div>

        {/* Generator Card */}
        <div className="bg-white rounded-3xl shadow-xl border border-slate-100 p-6 md:p-8 mb-10">
          <label className="block text-sm font-medium text-slate-700 mb-2">Topic / Keyword</label>
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && generate()}
              placeholder="e.g. Remote Work Productivity, React Hooks, Digital Marketing..."
              className="flex-1 px-5 py-3.5 rounded-2xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-slate-800"
            />
            <button
              onClick={generate}
              disabled={loading || !topic.trim()}
              className="px-8 py-3.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-300 text-white font-semibold rounded-2xl transition flex items-center justify-center gap-2 shadow-lg shadow-indigo-500/20"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate
                </>
              )}
            </button>
          </div>
        </div>

        {/* Result */}
        {result && (
          <div className="space-y-6">
            {/* SEO Score Card */}
            <div className="bg-white rounded-2xl border border-slate-100 p-6 flex flex-wrap items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-bold text-slate-900">{result.title}</h2>
                <p className="text-sm text-slate-500 mt-1">{result.word_count} words · SEO optimized</p>
              </div>
              <div className="flex items-center gap-4">
                <div className="text-center">
                  <div className="text-3xl font-bold text-indigo-600">{result.seo_score}</div>
                  <div className="text-xs text-slate-500">SEO Score</div>
                </div>
                <button
                  onClick={copyContent}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-slate-200 rounded-xl text-sm font-medium transition"
                >
                  {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
            </div>

            {/* Meta & Keywords */}
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-white rounded-2xl border border-slate-100 p-5">
                <h3 className="text-sm font-semibold text-slate-500 mb-2">Meta Description</h3>
                <p className="text-slate-700">{result.meta_description}</p>
              </div>
              <div className="bg-white rounded-2xl border border-slate-100 p-5">
                <h3 className="text-sm font-semibold text-slate-500 mb-2">Keywords</h3>
                <p className="text-slate-700">{result.keywords}</p>
              </div>
            </div>

            {/* Content */}
            <div className="bg-white rounded-2xl border border-slate-100 p-6 md:p-8">
              <div className="flex items-center gap-2 mb-4 text-slate-500">
                <FileText className="w-4 h-4" />
                <span className="text-sm font-medium">Generated Article</span>
              </div>
              <div className="prose prose-slate max-w-none whitespace-pre-wrap text-slate-700 leading-relaxed">
                {result.content}
              </div>
            </div>
          </div>
        )}

        {/* Footer */}
        <footer className="mt-16 text-center text-sm text-slate-500">
          Built by <strong>Rajiv Kapur</strong> · Software Architect & Full Stack Developer
        </footer>
      </main>
    </div>
  );
}
